language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - dev

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
    - cd bazzangee
    - ./gradlew clean build


before_deploy:
  - zip -r baezzangee bazzangee
  - mkdir -p deploy
  - mv baezzangee.zip deploy/baezzangee.zip



# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      slack: woowahan-techcamp:lcZvo31NIyp6sAgGAyRHSwtP

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: baezzangee # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: serverwizard/team7-WoowaSmell #Github 주소
      branch: dev

